[package]
name = "homo-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "homo"

[dependencies]
once_cell = "1.13.1"
pomsky-macro = "0.6.0"
regex = "1.6.0"
uint = "0.9.3"

[[bin]]
name = "cli"
test = false
bench = false
